### ISSUE TITLE
Incompatible with Windows Authentication

### ISSUE THREAD

**Issue by TDH-SSI-Hub** [waffy1901/JID-3314-CDC-Data-Reconciliation#114]
The server config is asking for a database username and password. We use Windows authentication without a password at our site. How do I change things to support this? I already have an established ODBC connection to our SQL server if that helps at all.

**Comment by Carson21** [comment]
We will add "Trusted_Connection=yes" to our connection string we use to connect to the database. Hopefully this will allow states that use windows authentication to be able to connect to the state database.

**Comment by Carson21** [comment]
PR: #116

**Comment by TDH-SSI-Hub** [comment]
I can't test this now, but we did edit the server.py to set the odbc like this:

connection_string = 'DRIVER={' + app.config["driver"] + \
    '}' + \
    f';SERVER={app.config["server"]};DATABASE={app.config["database"]};Trusted_Connection=yes'

It worked, and I was able to run everything else. So your fix will probably work fine for other users. Thanks!

**Comment by waffy1901** [comment]
That was exactly what we changed it to, great!

**Comment by waffy1901** [comment]
We implemented a more verbose solution in PR #118.
