### ISSUE TITLE
Main report table resizes differently from disease-specific stats table

### ISSUE THREAD

**Issue by p-zach** [waffy1901/JID-3314-CDC-Data-Reconciliation#46]
Reproduce:
1. Create a report
2. Open the report
3. Open disease-specific stats table
4. Resize window to be smaller

Expected behavior: both tables resize the same way

Observed behavior: disease-specific stats table resizes appropriately to fit the screen but case count table does not

**Comment by Carson21** [comment]
Has been fixed in PR #104
